baseurl: https://ttscience.blog/
languageCode: en-US
title: TT Science dev blog
theme: "hugo-PaperMod"
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/
services:
  googleAnalytics:
    id: "G-3MKP9QPBP1"
menu:
  main:
    - identifier: about
      name: ğŸ§‘ About us
      url: /about/
      weight: 1
    - identifier: archives
      name: ğŸ“– Archives
      url: /archives/
      weight: 2
    - identifier: search
      name: ğŸ” Search
      url: /search/
      weight: 3
params:
  env: production
  math: true
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 3.2.2
  description: Development blog of Transition Technologies Science Clinical Data Science Team.
  defaultTheme: auto
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  homeInfoParams:
    Title: "Hey there, data enthusiasts! ğŸ‘‹"
    Content: "Here at TT Science, we are a dynamic team of individuals â€” like trees in a [random forest](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html) ğŸŒ³ğŸŒ² â€” each bringing our own unique strengths and perspectives to the table. While we share a common goal of advancing clinical data science, itâ€™s our diversity that makes us truly special! <br><br> ğŸŒˆ Join us on this exciting journey ğŸš€ as we share insights, tutorials, and updates on our innovative projects involving R, Python, and biostatistics. ğŸ’»ğŸ” Explore our posts, dive into our GitHub projects ğŸ“‚, and get to know the passionate minds behind our work. Together, weâ€™re harnessing the power of data to create impactful solutions in healthcare. ğŸ’¡ğŸ’– Welcome to our forest of knowledge! ğŸŒ³ğŸŒŸ"
  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
  socialIcons:
    - name: "Company website"
      url: "https://ttsi.com.pl/"
    - name: "GitHub"
      url: "https://github.com/ttscience"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/company/transition-technologies-science-sp-z-o-o/"
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  ShowShareButtons: true
markup:
  highlight:
    noClasses: false # Use classes for more customizable styling via CSS
    style: "github" # Choose a Chroma theme you like (e.g., "monokai", "dracula", "github")
    codeFences: true # Enable syntax highlighting for code fences
    guessSyntax: true # Automatically guess the language if not specified
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
